
import argparse
import requests
import xml.etree.ElementTree as ET
import csv
from typing import List, Dict


def search_pubmed(query: str, email: str, retmax: int = 50) -> List[str]:
    """Search PubMed and return a list of PubMed IDs."""
        url = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi"
            params = {
                    "db": "pubmed",
                            "term": query,
                                    "retmode": "xml",
                                            "retmax": retmax,
                                                    "email": email
                                                        }
                                                            response = requests.get(url, params=params)
                                                                response.raise_for_status()
                                                                    root = ET.fromstring(response.content)
                                                                        return [id_elem.text for id_elem in root.findall(".//Id")]


                                                                        def fetch_pubmed_details(ids: List[str], email: str) -> List[Dict]:
                                                                            """Fetch full details of PubMed papers given their IDs."""
                                                                                url = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi"
                                                                                    params = {
                                                                                            "db": "pubmed",
                                                                                                    "id": ",".join(ids),
                                                                                                            "retmode": "xml",
                                                                                                                    "email": email
                                                                                                                        }
                                                                                                                            response = requests.get(url, params=params)
                                                                                                                                response.raise_for_status()
                                                                                                                                    return parse_articles(response.content)


                                                                                                                                    def parse_articles(xml_data: bytes) -> List[Dict]:
                                                                                                                                        """Parse XML data and extract required information."""
                                                                                                                                            root = ET.fromstring(xml_data)
                                                                                                                                                papers = []

                                                                                                                                                    for article in root.findall(".//PubmedArticle"):
                                                                                                                                                            try:
                                                                                                                                                                        pmid = article.findtext(".//PMID")
                                                                                                                                                                                    title = article.findtext(".//ArticleTitle")
                                                                                                                                                                                                pub_date = article.findtext(".//PubDate/Year") or "N/A"
                                                                                                                                                                                                            authors = article.findall(".//Author")

                                                                                                                                                                                                                        non_academic_authors = set()
                                                                                                                                                                                                                                    company_affiliations = set()
                                                                                                                                                                                                                                                corresponding_email = ""

                                                                                                                                                                                                                                                            for author in authors:
                                                                                                                                                                                                                                                                            affil = author.findtext(".//AffiliationInfo/Affiliation") or ""
                                                                                                                                                                                                                                                                                            affil_lower = affil.lower()

                                                                                                                                                                                                                                                                                                            if any(word in affil_lower for word in ["inc", "corp", "ltd", "biotech", "pharma"]):
                                                                                                                                                                                                                                                                                                                                company_affiliations.add(affil)

                                                                                                                                                                                                                                                                                                                                                elif not any(word in affil_lower for word in ["university", "college", "school", "institute", "lab"]):
                                                                                                                                                                                                                                                                                                                                                                    non_academic_authors.add(affil)

                                                                                                                                                                                                                                                                                                                                                                                    if "@" in affil and not corresponding_email:
                                                                                                                                                                                                                                                                                                                                                                                                        words = affil.split()
                                                                                                                                                                                                                                                                                                                                                                                                                            corresponding_email = next((word for word in words if "@" in word), "")

                                                                                                                                                                                                                                                                                                                                                                                                                                        if company_affiliations:
                                                                                                                                                                                                                                                                                                                                                                                                                                                        papers.append({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "PubmedID": pmid,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "Title": title,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "Publication Date": pub_date,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "Non-academic Author(s)": "; ".join(non_academic_authors),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "Company Affiliation(s)": "; ".join(company_affiliations),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "Corresponding Author Email": corresponding_email
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                })

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    continue  # Skip any problematic records

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return papers


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def save_to_csv(data: List[Dict], filename: str) -> None:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            """Save data to a CSV file."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if not data:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("No data to write.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    with open(filename, mode="w", newline="", encoding="utf-8") as file:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            writer = csv.DictWriter(file, fieldnames=data[0].keys())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    writer.writeheader()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            writer.writerows(data)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print(f"Saved {len(data)} records to {filename}")


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def main():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    parser = argparse.ArgumentParser(description="Fetch PubMed papers with biotech/pharma affiliations.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        parser.add_argument("query", type=str, help="Search query for PubMed")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            parser.add_argument("-f", "--file", type=str, help="CSV file to save results")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                parser.add_argument("-d", "--debug", action="store_true", help="Enable debug output")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    args = parser.parse_args()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        email = "your_email@example.com"  # Replace with your actual email

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if args.debug:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print(f"Searching PubMed for query: {args.query}")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ids = search_pubmed(args.query, email=email)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if args.debug:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print(f"Found {len(ids)} papers.")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            papers = fetch_pubmed_details(ids, email=email)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if args.file:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                save_to_csv(papers, args.file)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for paper in papers:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print(paper)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print(f"Error: {e}")


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    main()